# Generated by Django 4.2.15 on 2024-08-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Movie',
        ),
    ]
